Repository ucfopen/Obojobo, pull requests merged in 2020-03, with the labels that each got.

#923 File upload manager
  package.json
  packages/app/obojobo-document-engine/__tests__/common/components/modal/simple-dialog.test.js
  packages/app/obojobo-document-engine/src/scripts/common/components/modal/modal.scss
  packages/app/obojobo-express/__tests__/models/media.test.js
  packages/app/obojobo-express/__tests__/routes/api/media.test.js
  packages/app/obojobo-express/server/express_validators.js
  packages/app/obojobo-express/server/models/media.js
  packages/app/obojobo-express/server/routes/api/media.js
  packages/obonode/obojobo-chunks-figure/__snapshots__/choose-image-modal.test.js.snap
  packages/obonode/obojobo-chunks-figure/__snapshots__/image-properties-modal.test.js.snap
  packages/obonode/obojobo-chunks-figure/choose-image-modal.js
  packages/obonode/obojobo-chunks-figure/choose-image-modal.scss
  packages/obonode/obojobo-chunks-figure/choose-image-modal.test.js
  packages/obonode/obojobo-chunks-figure/image-properties-modal.js
  packages/obonode/obojobo-chunks-figure/image-properties-modal.scss
  packages/obonode/obojobo-chunks-figure/image-properties-modal.test.js
  packages/obonode/obojobo-chunks-figure/image.js
  packages/obonode/obojobo-chunks-figure/utils.js
  packages/obonode/obojobo-chunks-figure/utils.test.js
  packages/obonode/obojobo-sections-assessment/server/express.js
  packages/obonode/obojobo-sections-assessment/server/express.test.js
Labels: enhancement, front end, needs merge

#1120 [optimize] uses db.taskIf for multi-query functions
  packages/app/obojobo-document-engine/__mocks__/db.js
  packages/app/obojobo-express/__tests__/insert_event.test.js
  packages/app/obojobo-express/__tests__/models/visit.test.js
  packages/app/obojobo-express/__tests__/routes/api/events.test.js
  packages/app/obojobo-express/server/insert_event.js
  packages/app/obojobo-express/server/models/visit.js
  packages/app/obojobo-repository/server/services/search.js
Labels: db, needs merge

#1152 Answering a question doesn't change a figure caption
  packages/obonode/obojobo-chunks-question/viewer-component.scss
Labels: needs merge

#1156 Fixed issues with math equation sitting under content
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/node/editor-component.js
  packages/obonode/obojobo-chunks-question/editor-component.js
  packages/obonode/obojobo-chunks-question/editor-component.scss
Labels: needs merge

#1169 MoreInfoBox duplicate keys
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/navigation/more-info-box.js
Labels: needs merge

#1173 Xml encode special character
  packages/app/obojobo-document-json-parser/__tests__/__snapshots__/json-to-xml.test.js.snap
  packages/app/obojobo-document-json-parser/src/text-group-parser.js
  packages/app/obojobo-document-json-parser/src/xml-encode.js
Labels: needs merge

#1176 adds plugin-transform-runtime to optimize build
  packages/app/obojobo-document-engine/babel.config.js
  packages/app/obojobo-express/babel.config.js
  packages/app/obojobo-express/webpack.config.js
Labels: Cleanup / Polish, needs merge

#1105 Update variable substitution code to not break Latex
  packages/app/obojobo-document-engine/__tests__/common/chunk/text-chunk/text-group-el.test.js
  packages/app/obojobo-document-engine/src/scripts/common/chunk/text-chunk/text-group-el.js
  packages/app/obojobo-document-engine/src/scripts/common/text/styleable-text-renderer.js
  packages/obonode/obojobo-chunks-html/viewer-component.js
  packages/obonode/obojobo-chunks-math-equation/__snapshots__/viewer-component.test.js.snap
  packages/obonode/obojobo-chunks-math-equation/viewer-component.js
Labels: needs merge

#1178 Long single word title blocks content
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/editor-app.scss
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/navigation/editor-nav.scss
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/navigation/more-info-box.scss
  packages/app/obojobo-document-engine/src/scripts/viewer/components/header.scss
  packages/app/obojobo-document-engine/src/scripts/viewer/components/inline-nav-button.scss
  packages/app/obojobo-document-engine/src/scripts/viewer/components/nav.scss
  packages/app/obojobo-document-engine/src/scripts/viewer/components/viewer-app.scss
  packages/app/obojobo-document-engine/src/scss/main.scss
  packages/app/obojobo-module-selector/client/css/module-selector.scss
  packages/app/obojobo-repository/shared/components/module-permissions-dialog.jsx
  packages/app/obojobo-repository/shared/components/module-permissions-dialog.scss
  packages/app/obojobo-repository/shared/components/module.scss
  packages/app/obojobo-repository/shared/components/repository-banner.scss
Labels: needs merge

#1160 XML editor now preserves unexpected tags and their attributes instead of breaking.
  packages/app/obojobo-document-engine/__tests__/common/text/chunk-style-list.test.js
  packages/app/obojobo-document-engine/__tests__/common/text/style-range.test.js
  packages/app/obojobo-document-engine/__tests__/common/text/styleable-text-renderer.test.js
  packages/app/obojobo-document-engine/src/scripts/common/text/chunk-style-list.js
  packages/app/obojobo-document-engine/src/scripts/common/text/style-range.js
  packages/app/obojobo-document-engine/src/scripts/common/text/styleable-text-renderer.js
  packages/app/obojobo-document-xml-parser/__tests__/src/text-group-parser.test.js
  packages/app/obojobo-document-xml-parser/package.json
  packages/app/obojobo-document-xml-parser/src/text-group-parser.js
Labels: needs merge

#1187 replaces momentjs with dayjs to reduce module-page js size
  packages/app/obojobo-repository/package.json
  packages/app/obojobo-repository/shared/components/pages/page-module.jsx
  yarn.lock
Labels: Cleanup / Polish, front end, needs merge, repository

#1214 [fix] review api no longer returns id-keyed objects
  packages/app/obojobo-document-engine/__tests__/Viewer/stores/assessment-store.test.js
  packages/app/obojobo-document-engine/__tests__/Viewer/util/api-util.test.js
  packages/app/obojobo-document-engine/src/scripts/viewer/stores/assessment-store.js
  packages/app/obojobo-document-engine/src/scripts/viewer/util/api-util.js
  packages/obonode/obojobo-sections-assessment/server/__snapshots__/assessment.test.js.snap
  packages/obonode/obojobo-sections-assessment/server/assessment.js
  packages/obonode/obojobo-sections-assessment/server/assessment.test.js
  packages/obonode/obojobo-sections-assessment/server/express.js
  packages/obonode/obojobo-sections-assessment/server/express.test.js
Labels: high priority

#1213 Fixes XML conversion for questions conserving the type param
  packages/app/obojobo-document-json-parser/src/parsers/question-node-parser.js
Labels: high priority

#1215 Ensures clicking outside the more info box will update the settings
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/navigation/__snapshots__/more-info-box.test.js.snap
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/navigation/more-info-box.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/navigation/more-info-box.scss
Labels: high priority

#1204 Update visual tutorial
  packages/app/obojobo-document-engine/src/scripts/oboeditor/documents/oboeditor-tutorial.json
Labels: high priority
