Repository ucfopen/Obojobo, pull requests merged in 2020-01, with the labels that each got.

#1050 [fix] editor question bank settings radio buttons
  packages/obonode/obojobo-chunks-question-bank/__snapshots__/converter.test.js.snap
  packages/obonode/obojobo-chunks-question-bank/components/settings/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-question-bank/components/settings/editor-component.js
  packages/obonode/obojobo-chunks-question-bank/components/settings/editor-component.scss
  packages/obonode/obojobo-chunks-question-bank/components/settings/editor-component.test.js
  packages/obonode/obojobo-chunks-question-bank/converter.js
  packages/obonode/obojobo-chunks-question-bank/converter.test.js
  packages/obonode/obojobo-chunks-question-bank/empty-node.json
  packages/obonode/obojobo-chunks-question-bank/schema.js
Labels: high priority

#1063 Fixes scrolling focus issues for Break, MathEquation and YouTube in the Visual Editor
  packages/app/obojobo-document-engine/__tests__/oboeditor/util/include-text-cancelling-plugins.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/editable-hidden-text.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/editable-hidden-text.scss
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/node/editor-component.scss
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/page-editor.scss
  packages/app/obojobo-document-engine/src/scripts/oboeditor/util/include-text-cancelling-plugins.js
  packages/obonode/obojobo-chunks-break/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-break/editor-component.js
  packages/obonode/obojobo-chunks-break/editor-component.scss
  packages/obonode/obojobo-chunks-break/editor-registration.js
  packages/obonode/obojobo-chunks-break/empty-node.json
  packages/obonode/obojobo-chunks-break/schema.js
  packages/obonode/obojobo-chunks-math-equation/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-math-equation/editor-component.js
  packages/obonode/obojobo-chunks-math-equation/editor-component.test.js
  packages/obonode/obojobo-chunks-math-equation/editor-registration.js
  packages/obonode/obojobo-chunks-math-equation/empty-node.json
  packages/obonode/obojobo-chunks-math-equation/schema.js
  packages/obonode/obojobo-chunks-youtube/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-youtube/editor-component.js
  packages/obonode/obojobo-chunks-youtube/editor-registration.js
  packages/obonode/obojobo-chunks-youtube/empty-node.json
  packages/obonode/obojobo-chunks-youtube/schema.js
Labels: high priority

#1057 Fixes a few issues with copy & paste in the visual editor
  packages/app/obojobo-document-engine/__tests__/common/registry.test.js
  packages/app/obojobo-document-engine/src/scripts/common/registry.js
  packages/obonode/obojobo-chunks-heading/editor-registration.js
  packages/obonode/obojobo-chunks-heading/editor-registration.test.js
  packages/obonode/obojobo-chunks-text/editor-registration.js
Labels: high priority

#1065 Adds preventESC to Modal (and super classes) to stop users from using the ESC key to close a dialog
  packages/app/obojobo-document-engine/__tests__/common/components/modal/modal.test.js
  packages/app/obojobo-document-engine/src/scripts/common/components/modal/dialog.js
  packages/app/obojobo-document-engine/src/scripts/common/components/modal/modal.js
  packages/app/obojobo-document-engine/src/scripts/common/components/modal/simple-dialog.js
  packages/app/obojobo-document-engine/src/scripts/viewer/stores/assessment-store.js
Labels: high priority

#1067 Issue/1058 switching trigger actions does not clear out previous values
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/triggers/__snapshots__/trigger-list-modal.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/triggers/trigger-list-modal.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/triggers/trigger-list-modal.js
Labels: high priority

#1074 Strips empty `mods` in json-to-xml-parser but still allows it to be saved
  packages/app/obojobo-document-json-parser/src/parsers/assessment-node-parser.js
  packages/app/obojobo-document-xml-parser/src/assessment-rubric-parser.js
Labels: bug, editor, high priority

#1073 Prevent QuestionBank settings component from creating infinite loop
  packages/obonode/obojobo-chunks-question-bank/components/settings/editor-component.js
  packages/obonode/obojobo-chunks-question-bank/components/settings/editor-component.test.js
Labels: high priority

#1082 Fix save problems on visual/xml/json editor
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/code-editor.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/toolbars/file-menu.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/toolbars/view-menu.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/code-editor.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/toolbars/file-menu.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/toolbars/view-menu.js
Labels: bug, editor, high priority

#1000 api/visit/start errors sooner when student visits an old draft version
  packages/app/obojobo-express/server/routes/api/visits.js
Labels: Cleanup / Polish

#1042 [reporting] Adds a custom type definition for cloc
  cloc-type-definitions.txt
Labels: documentation, enhancement

#1078 [clean] removes /api/drafts/:draft/raw route
  packages/app/obojobo-express/__tests__/routes/api/drafts.test.js
  packages/app/obojobo-express/routes/api/drafts.js
Labels: high priority

#1069 [fix] fixes viewer idle timer reactiviation
  packages/app/obojobo-document-engine/src/scripts/viewer/components/viewer-app.js
Labels: high priority

#1002 Fixes responsive design issues
  package.json
  packages/app/obojobo-document-engine/src/scripts/viewer/components/header.scss
  packages/app/obojobo-document-engine/src/scripts/viewer/components/inline-nav-button.scss
  packages/app/obojobo-document-engine/src/scripts/viewer/components/viewer-app.js
  packages/obonode/obojobo-chunks-list/viewer-component.scss
  packages/obonode/obojobo-chunks-multiple-choice-assessment/viewer-component.scss
Labels: Mobile, css, front end

#1097 Visual Editor - Updates text for rubric and corrects values
  packages/obonode/obojobo-sections-assessment/components/rubric/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-sections-assessment/components/rubric/editor-component.js
Labels: high priority

#1107 Pasting text in figure caption breaks editor
  packages/obonode/obojobo-chunks-figure/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-figure/editor-component.js
  packages/obonode/obojobo-chunks-figure/editor-component.test.js
  packages/obonode/obojobo-chunks-figure/editor-registration.js
  packages/obonode/obojobo-chunks-figure/editor-registration.test.js
Labels: bug, editor

#1117 Fix obojobo-migrate bad path
  packages/app/obojobo-express/index.js
  packages/util/obojobo-lib-utils/bin/obojobo-migrate
Labels: bug

#1116 Creating a new module in xml/json editor causes 404
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/toolbars/file-menu.js
Labels: bug
