Repository ucfopen/Obojobo, pull requests merged in 2020-05, with the labels that each got.

#1236 Add processAttrs to all nodeParsers
  packages/app/obojobo-document-json-parser/__tests__/__snapshots__/json-to-xml.test.js.snap
  packages/app/obojobo-document-json-parser/src/parsers/code-node-parser.js
  packages/app/obojobo-document-json-parser/src/parsers/content-node-parser.js
  packages/app/obojobo-document-json-parser/src/parsers/heading-node-parser.js
  packages/app/obojobo-document-json-parser/src/parsers/list-node-parser.js
  packages/app/obojobo-document-json-parser/src/parsers/mc-answer-node-parser.js
  packages/app/obojobo-document-json-parser/src/parsers/mc-feedback-node-parser.js
  packages/app/obojobo-document-json-parser/src/parsers/node-parser.js
  packages/app/obojobo-document-json-parser/src/parsers/process-attrs.js
  packages/app/obojobo-document-json-parser/src/parsers/table-node-parser.js
  packages/app/obojobo-document-json-parser/src/parsers/text-group-parser.js
  packages/app/obojobo-document-json-parser/src/parsers/text-node-parser.js
  packages/app/obojobo-document-json-parser/src/parsers/xml-encode.js
  packages/app/obojobo-document-json-parser/src/parsers/youtube-node-parser.js
  packages/app/obojobo-document-json-parser/src/process-attrs.js
Labels: json-parser

#1329 Fixes Editor Done button
  packages/obonode/obojobo-chunks-heading/editor-registration.js
  packages/obonode/obojobo-chunks-heading/editor-registration.test.js
  packages/obonode/obojobo-chunks-question/editor-registration.js
  packages/obonode/obojobo-chunks-question/editor-registration.test.js
Labels: Review Me First, high priority

#1285 Remove cursor in non-editable items
  packages/obonode/obojobo-chunks-iframe/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-iframe/editor-component.js
  packages/obonode/obojobo-chunks-question-bank/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-question-bank/editor-component.js
  packages/obonode/obojobo-chunks-question/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-question/editor-component.js
  packages/obonode/obojobo-sections-assessment/components/rubric/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-sections-assessment/components/rubric/editor-component.js
Labels: editor

#1293 Add 404 page for deleted modules
  packages/app/obojobo-express/__tests__/express_validators.test.js
  packages/app/obojobo-express/__tests__/routes/api/visits.test.js
  packages/app/obojobo-express/__tests__/routes/preview.test.js
  packages/app/obojobo-express/__tests__/routes/viewer.test.js
  packages/app/obojobo-express/server/express_validators.js
Labels: express package

#1193 Enhance Visual Editor Link/URL Menu & UI
  packages/app/obojobo-document-engine/__tests__/common/text/__snapshots__/styleable-text-component.test.js.snap
  packages/app/obojobo-document-engine/__tests__/common/text/styleable-text-component.test.js
  packages/app/obojobo-document-engine/__tests__/common/util/with-protocol.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/marks/__snapshots__/link.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/marks/link.test.js
  packages/app/obojobo-document-engine/src/scripts/common/index.js
  packages/app/obojobo-document-engine/src/scripts/common/text/styleable-text-component.js
  packages/app/obojobo-document-engine/src/scripts/common/util/with-protocol.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/marks/copy.svg
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/marks/edit.svg
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/marks/link.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/marks/link.scss
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/marks/unlink.svg
  packages/obonode/obojobo-chunks-iframe/viewer-component.js
  packages/util/obojobo-lib-utils/index.js
Labels: Review Me First

#1284 [Fix] saving issue while editing MathEquation
  packages/obonode/obojobo-chunks-math-equation/editor-component.js
  packages/obonode/obojobo-chunks-math-equation/editor-component.test.js
Labels: Review Me First, bug, editor, high priority

#1310 Make keys for ActionButtonEditorAction components more specific to avoid collisions for duplicate actions.
  packages/obonode/obojobo-chunks-action-button/editor-component.js
Labels: Review Me First, editor

#1322 Fix assessment variables outside breaks the viewer
  packages/obonode/obojobo-sections-assessment/viewer.js
  packages/obonode/obojobo-sections-assessment/viewer.test.js
Labels: Review Me First

#1288 Adds visitId to assessment:attemptEnd event
  packages/app/obojobo-express/__tests__/lti.test.js
  packages/app/obojobo-express/__tests__/routes/__snapshots__/viewer.test.js.snap
  packages/app/obojobo-express/server/lti.js
  packages/app/obojobo-express/server/routes/preview.js
  packages/app/obojobo-express/server/routes/viewer.js
  packages/obonode/obojobo-sections-assessment/server/attempt-end/attempt-end-helpers.js
  packages/obonode/obojobo-sections-assessment/server/attempt-end/attempt-end-helpers.test.js
  packages/obonode/obojobo-sections-assessment/server/attempt-end/insert-events.js
  packages/obonode/obojobo-sections-assessment/server/attempt-end/insert-events.test.js
  packages/obonode/obojobo-sections-assessment/server/attempt-resume.js
  packages/obonode/obojobo-sections-assessment/server/attempt-resume.test.js
  packages/obonode/obojobo-sections-assessment/server/express.js
  packages/obonode/obojobo-sections-assessment/server/express.test.js
Labels: Review Me First, high priority

#1325 CSS/JS size and bundle optimizations
  packages/app/obojobo-document-engine/__tests__/Viewer/components/viewer-app.test.js
  packages/app/obojobo-document-engine/__tests__/common/text/styleable-text-renderer.test.js
  packages/app/obojobo-document-engine/__tests__/common/util/inject-katex-if-needed.test.js
  packages/app/obojobo-document-engine/__tests__/common/util/insert-dom-tag.test.js
  packages/app/obojobo-document-engine/__tests__/common/util/shuffle.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/__snapshots__/code-editor.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/__snapshots__/hovering-preview.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/code-editor.test.js
  packages/app/obojobo-document-engine/package.json
  packages/app/obojobo-document-engine/setupTests.js
  packages/app/obojobo-document-engine/src/scripts/common/text/styleable-text-renderer.js
  packages/app/obojobo-document-engine/src/scripts/common/util/inject-katex-if-needed.js
  packages/app/obojobo-document-engine/src/scripts/common/util/insert-dom-tag.js
  packages/app/obojobo-document-engine/src/scripts/common/util/shuffle.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/code-editor.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/code-mirror-bundle.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/hovering-preview.js
  packages/app/obojobo-document-engine/src/scripts/viewer/components/rd.scss
  packages/app/obojobo-document-engine/src/scripts/viewer/components/viewer-app.js
  packages/app/obojobo-document-json-parser/__tests__/json-to-xml.test.js
  packages/app/obojobo-express/server/views/editor.ejs
  packages/app/obojobo-express/server/views/viewer.ejs
  packages/app/obojobo-express/webpack.config.js
  packages/app/obojobo-repository/server/public/images/rd.png
  packages/obonode/obojobo-chunks-html/__snapshots__/viewer-component.test.js.snap
  packages/obonode/obojobo-chunks-html/viewer-component.js
  packages/obonode/obojobo-chunks-math-equation/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-math-equation/__snapshots__/viewer-component.test.js.snap
  packages/obonode/obojobo-chunks-math-equation/editor-component.js
  packages/obonode/obojobo-chunks-math-equation/editor-component.test.js
  packages/obonode/obojobo-chunks-math-equation/viewer-component.js
  packages/obonode/obojobo-chunks-math-equation/viewer-component.test.js
  packages/obonode/obojobo-chunks-multiple-choice-assessment/viewer-component.js
  packages/obonode/obojobo-chunks-multiple-choice-assessment/viewer-component.test.js
  packages/obonode/obojobo-chunks-question-bank/server/question-bank.js
  packages/obonode/obojobo-chunks-question-bank/server/question-bank.test.js
  packages/obonode/obojobo-chunks-question/viewer-component.test.js
  packages/obonode/obojobo-chunks-youtube/editor-component.test.js
  packages/obonode/obojobo-chunks-youtube/viewer-component.test.js
  packages/obonode/obojobo-chunks-youtube/youtube-player.js
  packages/obonode/obojobo-chunks-youtube/youtube-player.test.js
  packages/obonode/obojobo-sections-assessment/server/attempt-start.test.js
  packages/obonode/obojobo-sections-assessment/viewer-component.test.js
  packages/util/obojobo-lib-utils/test-setup-chunks.js
  yarn.lock
Labels: Review Me First, high priority

#1331 [fix] visual editor incorrectly restores module
  packages/app/obojobo-document-engine/__tests__/common/models/obo-model.test.js
  packages/app/obojobo-document-engine/src/scripts/common/models/obo-model.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/editor-app.js
Labels: Review Me First, bug, high priority

#1344 [fix] can't save once page is duplicated
  packages/app/obojobo-express/__tests__/models/draft.test.js
  packages/app/obojobo-express/server/models/draft.js
Labels: Review Me First, bug, high priority

#1335 allow fractional MathEquation sizes, min/max input
  packages/app/obojobo-document-engine/src/scripts/common/util/insert-dom-tag.js
  packages/app/obojobo-express/webpack.config.js
  packages/obonode/obojobo-chunks-math-equation/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-math-equation/adapter.js
  packages/obonode/obojobo-chunks-math-equation/adapter.test.js
  packages/obonode/obojobo-chunks-math-equation/converter.js
  packages/obonode/obojobo-chunks-math-equation/editor-component.js
  packages/obonode/obojobo-chunks-math-equation/editor-component.test.js
  packages/obonode/obojobo-chunks-youtube/youtube-player.js
Labels: Review Me First, chunk specific, high priority, viewer

#1332 Speedup visual editor
  packages/app/obojobo-document-engine/__tests__/common/components/modal/__snapshots__/prompt.test.js.snap
  packages/app/obojobo-document-engine/__tests__/common/components/modal/prompt.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/__snapshots__/visual-editor.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/navigation/sub-menu.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/toolbars/__snapshots__/file-toolbar.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/toolbars/file-toolbar-viewer.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/toolbars/file-toolbar.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/toolbars/format-menu.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/visual-editor.test.js
  packages/app/obojobo-document-engine/src/scripts/common/components/modal/bubble/single-input-bubble.js
  packages/app/obojobo-document-engine/src/scripts/common/components/modal/dialog.js
  packages/app/obojobo-document-engine/src/scripts/common/components/modal/prompt.js
  packages/app/obojobo-document-engine/src/scripts/common/components/modal/simple-dialog.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/code-editor.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/editor-app.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/marks/link.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/navigation/sub-menu.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/node/editor-component.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/toolbars/file-menu.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/toolbars/file-toolbar-viewer.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/toolbars/file-toolbar.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/toolbars/format-menu.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/visual-editor.js
  packages/obonode/obojobo-chunks-action-button/editor-component.js
  packages/obonode/obojobo-chunks-break/editor-component.js
  packages/obonode/obojobo-chunks-figure/choose-image-modal.js
  packages/obonode/obojobo-chunks-figure/editor-component.js
  packages/obonode/obojobo-chunks-iframe/editor-component.js
  packages/obonode/obojobo-chunks-iframe/iframe-properties-modal.js
  packages/obonode/obojobo-chunks-multiple-choice-assessment/MCFeedback/editor-component.js
  packages/obonode/obojobo-chunks-multiple-choice-assessment/editor-component.js
  packages/obonode/obojobo-chunks-question-bank/editor-component.js
  packages/obonode/obojobo-chunks-table/create-form.js
  packages/obonode/obojobo-chunks-table/editor-component.js
  packages/obonode/obojobo-chunks-table/grid-button.js
  packages/obonode/obojobo-chunks-table/grid-button.scss
  packages/obonode/obojobo-chunks-table/table-controls.js
  packages/obonode/obojobo-chunks-table/table-menu.js
  packages/obonode/obojobo-chunks-youtube/editor-component.js
  packages/obonode/obojobo-chunks-youtube/youtube-properties-modal.js
  packages/obonode/obojobo-sections-assessment/components/rubric/editor-component.js
  packages/obonode/obojobo-sections-assessment/components/rubric/mod-properties.js
  packages/obonode/obojobo-sections-assessment/post-assessment/range-modal.js
Labels: Review Me First, editor, high priority, user experience

#1287 Figure caption has wrong width when using custom size
  packages/obonode/obojobo-chunks-figure/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-figure/__snapshots__/viewer-component.test.js.snap
  packages/obonode/obojobo-chunks-figure/editor-component.js
  packages/obonode/obojobo-chunks-figure/image.js
  packages/obonode/obojobo-chunks-figure/viewer-component.js
  packages/obonode/obojobo-chunks-figure/viewer-component.scss
  packages/obonode/obojobo-chunks-figure/viewer-component.test.js
Labels: Review Me First, rendering error

#1337 update outdated dependencies
  package.json
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/__snapshots__/visual-editor.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/node/components/insert-menu.test.js
  packages/app/obojobo-document-engine/package.json
  packages/app/obojobo-document-engine/setupTests.js
  packages/app/obojobo-document-engine/src/scripts/common/components/button.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/util/selection-util.js
  packages/app/obojobo-document-json-parser/package.json
  packages/app/obojobo-document-xml-parser/package.json
  packages/app/obojobo-express/package.json
  packages/app/obojobo-repository/package.json
  packages/obonode/obojobo-chunks-action-button/package.json
  packages/obonode/obojobo-chunks-break/package.json
  packages/obonode/obojobo-chunks-code/converter.js
  packages/obonode/obojobo-chunks-code/package.json
  packages/obonode/obojobo-chunks-figure/package.json
  packages/obonode/obojobo-chunks-heading/package.json
  packages/obonode/obojobo-chunks-html/package.json
  packages/obonode/obojobo-chunks-iframe/package.json
  packages/obonode/obojobo-chunks-list/converter.js
  packages/obonode/obojobo-chunks-list/package.json
  packages/obonode/obojobo-chunks-math-equation/__snapshots__/editor-component.test.js.snap
  packages/obonode/obojobo-chunks-math-equation/editor-component.js
  packages/obonode/obojobo-chunks-math-equation/editor-component.test.js
  packages/obonode/obojobo-chunks-math-equation/package.json
  packages/obonode/obojobo-chunks-multiple-choice-assessment/package.json
  packages/obonode/obojobo-chunks-question-bank/package.json
  packages/obonode/obojobo-chunks-question/package.json
  packages/obonode/obojobo-chunks-table/components/cell/editor-component.js
  packages/obonode/obojobo-chunks-table/package.json
  packages/obonode/obojobo-chunks-text/converter.js
  packages/obonode/obojobo-chunks-text/package.json
  packages/obonode/obojobo-chunks-youtube/package.json
  packages/obonode/obojobo-modules-module/package.json
  packages/obonode/obojobo-pages-page/package.json
  packages/obonode/obojobo-sections-assessment/package.json
  packages/obonode/obojobo-sections-content/package.json
  packages/util/eslint-config-obojobo/package.json
  packages/util/obojobo-lib-utils/package.json
  yarn.lock
Labels: Review Me First
