Repository ucfopen/Obojobo, pull requests merged in 2020-10, with the labels that each got.

#1555 Correct the display for showing the unableToPass score
  packages/app/obojobo-document-engine/__tests__/Viewer/util/assessment-util.test.js
  packages/app/obojobo-document-engine/__tests__/common/util/find-items-with-max-prop-value.test.js
  packages/app/obojobo-document-engine/src/scripts/common/util/find-items-with-max-prop-value.js
  packages/app/obojobo-document-engine/src/scripts/viewer/util/assessment-util.js
Labels: high priority

#1554 Fix the More Info Box when editing Assessment
  packages/app/obojobo-document-engine/__tests__/oboeditor/stores/editor-store.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/stores/editor-store.js
Labels: high priority

#1563 Ensures the assessment section converter isn't attempting to mutate the content object
  packages/obonode/obojobo-sections-assessment/__snapshots__/converter.test.js.snap
  packages/obonode/obojobo-sections-assessment/converter.js
  packages/obonode/obojobo-sections-assessment/converter.test.js
Labels: high priority

#1569 Ensures that the renaming of pages and modules work again
  packages/app/obojobo-document-engine/__tests__/oboeditor/stores/editor-store.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/stores/editor-store.js
Labels: high priority

#1588 Add shift key to align shortcut
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/__snapshots__/visual-editor.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/marks/align-marks.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/toolbars/__snapshots__/content-toolbar.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/toolbars/__snapshots__/format-menu.test.js.snap
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/marks/align-marks.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/documents/oboeditor-tutorial.json
Labels: reduce frustration

#1590 Bugs in breakToText
  packages/app/obojobo-document-engine/__tests__/oboeditor/util/keydown-util.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/util/keydown-util.js
Labels: feels broken
