Repository ucfopen/Obojobo, pull requests merged in 2020-06, with the labels that each got.

#1366 [fix] saving issue in xml/json editor
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/visual-editor.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/visual-editor.js
Labels: Review Me First, bug

#1368 XML editor crashes with visual editor tutorial
  packages/app/obojobo-document-engine/__tests__/common/text/styleable-text-renderer.test.js
  packages/app/obojobo-document-engine/src/scripts/common/text/styleable-text-renderer.js
Labels: Review Me First, bug, editor

#1372 [fix] repository links to classic editor
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/__snapshots__/editor-app.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/editor-app.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/editor-app.js
  packages/app/obojobo-repository/server/models/draft_summary.js
Labels: Review Me First

#1369 [fix] iframe and figure focus select issues
  packages/app/obojobo-document-engine/__tests__/oboeditor/util/freeze-unfreeze-editor.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/util/freeze-unfreeze-editor.js
  packages/obonode/obojobo-chunks-figure/editor-component.js
  packages/obonode/obojobo-chunks-figure/editor-component.test.js
  packages/obonode/obojobo-chunks-iframe/editor-component.js
  packages/obonode/obojobo-chunks-iframe/editor-component.test.js
  packages/obonode/obojobo-chunks-iframe/iframe-properties-modal.js
  packages/obonode/obojobo-chunks-math-equation/editor-component.js
Labels: Review Me First

#1389 [fix] multi-node select crash when moving nodes
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/node/editor-component.js
Labels: Review Me First

#1392 Triggers menu inputs requires double click
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/navigation/more-info-box.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/triggers/__snapshots__/trigger-list-modal.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/triggers/trigger-list-modal.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/navigation/more-info-box.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/triggers/trigger-list-modal.js
  packages/obonode/obojobo-chunks-action-button/editor-component.js
  packages/obonode/obojobo-chunks-action-button/editor-component.test.js
Labels: Review Me First

#1210 Module Restoration
  packages/app/obojobo-document-engine/__tests__/Viewer/util/api-util.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/__snapshots__/visual-editor.test.js.snap
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/editor-app.test.js
  packages/app/obojobo-document-engine/__tests__/oboeditor/components/visual-editor.test.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/editor-app.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/visual-editor.js
  packages/app/obojobo-document-engine/src/scripts/oboeditor/components/visual-editor.scss
  packages/app/obojobo-document-engine/src/scripts/viewer/util/api-util.js
  packages/app/obojobo-express/__tests__/models/draft.test.js
  packages/app/obojobo-express/__tests__/routes/editor.test.js
  packages/app/obojobo-express/bin/write_json_draft_to_db.js
  packages/app/obojobo-express/server/express_validators.js
  packages/app/obojobo-express/server/migrations/20180516144244-modify-drafts-content-convert-ids-to-uuids.js
  packages/app/obojobo-express/server/migrations/20200615234430-modify-drafts-content-add-user-id.js
  packages/app/obojobo-express/server/models/draft.js
  packages/app/obojobo-express/server/obo_express_dev.js
  packages/app/obojobo-express/server/routes/api/drafts.js
  packages/app/obojobo-express/server/routes/editor.js
  packages/app/obojobo-repository/client/css/_media-queries.scss
  packages/app/obojobo-repository/server/models/draft_summary.js
  packages/app/obojobo-repository/server/public/images/hex_transparent.svg
  packages/app/obojobo-repository/server/routes/api.js
  packages/app/obojobo-repository/shared/actions/dashboard-actions.js
  packages/app/obojobo-repository/shared/api-util.js
  packages/app/obojobo-repository/shared/components/dashboard-hoc.js
  packages/app/obojobo-repository/shared/components/dashboard.jsx
  packages/app/obojobo-repository/shared/components/loading.jsx
  packages/app/obojobo-repository/shared/components/module-options-dialog.js
  packages/app/obojobo-repository/shared/components/module-permissions-dialog.jsx
  packages/app/obojobo-repository/shared/components/module-permissions-dialog.scss
  packages/app/obojobo-repository/shared/components/pages/page-dashboard-server.jsx
  packages/app/obojobo-repository/shared/components/version-history-dialog.jsx
  packages/app/obojobo-repository/shared/components/version-history-dialog.scss
  packages/app/obojobo-repository/shared/components/version-history-list-item.js
  packages/app/obojobo-repository/shared/react-utils.js
  packages/app/obojobo-repository/shared/reducers/dashboard-reducer.js
Labels: Review Me First, enhancement
